### ISSUE TITLE
how to remove as a desktop session option?

### ISSUE THREAD

**Issue by shellheim** [lobiplayer/hyprland_rpm-package#1]
Hey! you have great work on the packaging and it works on my installation of fedora38.  
I was thinking of building it myself to I ran `sudo dnf remove hyprland` and this removed the `rpm` package but didn't remove it as an option for a desktop session on the login screen on startup.  
So I was wondering if you know how to do that. Thanks for the package!

**Comment by lobiplayer** [comment]
Hi @shellheim ,

Thanks for the feedback! I indeed forgot to have that desktop file removed after uninstalling. I will add this soon.

**Comment by shellheim** [comment]
Thanks for considering! I got help and figured out the file was in `usr/share/wayland-sessions`      .  Deleting the `hyprland.desktop` file worked.  Again thanks for packaging hyprland!
